### ISSUE TITLE
Not enough compiled Bash

### ISSUE THREAD

**Issue by m132** [Cvolton/s7camera2fix#1]
The world's most advanced library patching solutions used by this module are very resource intensive, causing the little CPUs found in phones to scream in terror and explode. This could be easily solved by optimizing the code via shell compilers, like _shc_.

Various studies have proven that using compiled Bash technologies results in a very high performance gains.

![very important chart](https://canvasjs.com/wp-content/uploads/images/gallery/php-charts/overview/php-charts-graphs-index-data-label.png)

**Comment by Cvolton** [comment]
>

**Comment by m132** [comment]
Thank you for this short, yet incredibly detailed reply! I'm happy to see this issue being worked on.

**Comment by Cvolton** [comment]
```gccsh install.sh```
